#+STARTUP: showeverything 
# -*- in-config-file: t -*-

* Wth?
This is the readme for the github repo where I attempt to make myself a functional emacs configuration from 
naked emacs. It's running on a raspberry pi, with the idea that after I make it sufficiently functional 
(which could be, like, years), then

This is also the configuration file itself, because I'm doing fancy org babel literate config stuff.

So, that's cool.

* Package management

** Make MELPA run

This is an incantation that appears to be required to get MELPA to work. I've got no idea why, but 
it comes from this place: 
https://francopasut.medium.com/emacs-melpa-and-the-failed-to-download-gnu-archive-error-b834bbe4491e

#+BEGIN_SRC emacs-lisp
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
#+END_SRC

The rest of the setup for melpa, as copied from evil installation instructions 

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)
#+END_SRC

** Use-Package seems necessary

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
#+END_SRC


* Evilify everything because emacs keybindings are horrible

Download and install evil 

#+BEGIN_SRC emacs-lisp

(use-package evil
  :ensure t ;; install the evil package if not installed
  :init 
  (setq evil-want-keybinding nil))  ;; this is apparently required for evil-collection keybindings.
  (evil-mode)

#+END_SRC

Let's get as much evilified as humanly possible just to start, eh?

#+BEGIN_SRC emacs-lisp
(use-package evil-commentary
  :ensure t)
(evil-commentary-mode)

(use-package evil-collection
  :ensure t)
(evil-collection-init)

(use-package evil-org
  :ensure t
  :after org
  :config
  (add-hook 'org-mode-hook 'evil-org-mode)
  (add-hook 'evil-org-mode-hook
            (lambda ()
              (evil-org-set-key-theme)))
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))
#+END_SRC

* I'm getting sick of typing all these code delimiters

Currently this doesn't work.  The idea was to have the add-lisp-delimiters 
function defined in my init.el, and then put the begin_src and end_src stuff in there
which then gets attached to the @ keybinding here, and only invoked when the 
in-config-file (set at the beginning of this org file) variable is true.

but I type @ in normal mode and nothing happens.  Hmm.

#+BEGIN_SRC emacs-lisp

(add-hook 'org-mode-hook 
  (lambda () 
    (evil-global-set-key 'normal (kbd "@") 'add-lisp-delimiters)))

#+END_SRC

