# -*- in-config-file: t; lexical-binding: t  -*-




* Wth?

I'm now running this emacs config on my mac!  I've escaped spacemacs!  Even though 
it's not done yet, it's functional enough that I can use it, and I got sick of worrying about what kinds 
of things would have to be changed after moving machines.

doing the literate org config, so this readme file is also my config file!  (Well, most of it.  I 
defined a little bit of stuff that applies to this file itself, like a snippet to get elisp code blocks 
that I didn't know how to escape, in init.el.)  So that's cool.


** Conventions

   - I use the tag *dev* for headlines that contain code that might go away when I'm happy with this config, like the snippet I bound to @ below.

   - I use the tag *key* for headlines that contain code with a keybinding in it.  This is for ease of later documentation.
     - At some point I want to create a personal usage manual.

   - I use the tag *fragile* for headlines containing code with non-obvious or even downright mysterious failure potential, where I made it work with pure guesswork.

   - As much as possible, I try to keep keybindings together rather than with their associated packages.  This might be a mistake?


Keybindings are now listed in keybindings.org in this repository



* Package management

[[https://github.com/raxod502/straight.el][Straight]] appears to be an /actual package manager/ unlike stuff like use-package.  I can get a lockfile with commit hashes for every package I use with ~(straight-freeze-versions)~ . 

Given that emacs packages seem to just /love/ generating side effects, this seems like a thing that is absolutely mandatory. I've already had one nasty package conflict scare.

#+BEGIN_SRC emacs-lisp

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

#+END_SRC


* Perf tweaks to be done early

#+BEGIN_SRC emacs-lisp
(straight-use-package 'gcmh)
(gcmh-mode 1)
#+END_SRC

attempt to fix an obnoxious screen flicker. borrowed from [[https://old.reddit.com/r/emacs/comments/ecctcp/how_to_debug_emacs_flickering_issue/fbasdxf/][here]] 

(does not appear to be helping ... actually it seems to be making it worse and I'm going to comment it out for now)

#+BEGIN_SRC emacs-lisp
; (add-to-list 'default-frame-alist '(inhibit-double-buffering . t))
#+END_SRC

keep gc out of minibuffer, and other GC tweaks borrowed from Doom and from the Walsh dude

#+BEGIN_SRC emacs-lisp
(defun defer-garbage-collection-hook ()
  (setq gc-cons-threshold most-positive-fixnum))

(defvar base-gc-threshold 67108864)

(defun restore-garbage-collection-hook ()
  (garbage-collect)
  (setq gc-cons-threshold base-gc-threshold))

(add-hook 'minibuffer-setup-hook #'defer-garbage-collection-hook)
(add-hook 'minibuffer-exit-hook #'restore-garbage-collection-hook)
#+END_SRC


* Make things involving the commandline work on mac.

#+BEGIN_SRC emacs-lisp

(straight-use-package 'exec-path-from-shell)
(exec-path-from-shell-initialize)

#+END_SRC

Make use of the trash can before I start trying to use things like dired
UNTESTED
#+BEGIN_SRC emacs-lisp

(straight-use-package 'osx-trash)
(when (eq system-type 'darwin)
  (osx-trash-setup))
(setq delete-by-moving-to-trash t)

#+END_SRC


* Emacs mechanical tweaks

Kill all the damn beeping

#+BEGIN_SRC emacs-lisp

(setq visible-bell 1)

#+END_SRC

Also kill all the annoying confirmations.  Borrowed from [[https://www.masteringemacs.org/article/disabling-prompts-emacs][here]]. 

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)

(setq confirm-nonexistent-file-or-buffer nil)

(setq kill-buffer-query-functions
  (remq 'process-kill-buffer-query-function
         kill-buffer-query-functions))
#+END_SRC

I'm over the backup files. Borrowing code from [[https://www.emacswiki.org/emacs/BackupDirectory][the wiki]] 

#+BEGIN_SRC emacs-lisp
(defvar backup-dir "~/Dropbox/emacs-backup-files")
    (setq backup-directory-alist
          `((".*" . ,backup-dir)))
    (setq auto-save-file-name-transforms
          `((".*" ,backup-dir t)))

; this *was* working, or at least failing silently.  then randomly, after I added 
; some keybindings down below it started blowing up with "symbol's function definition is void: fifth"
; which, wtf??  so I'm just going to kill it for now.

;(message "Deleting old backup files...")
;(let ((week (* 60 60 24 7))
;      (current (float-time (current-time))))
;  (dolist (file (directory-files backup-dir t))
;    (when (and (backup-file-name-p file)
;               (> (- current (float-time (fifth (file-attributes file))))
;                  week))
;      (message "%s" file)
;      (delete-file file))))
#+END_SRC

Undo-redo is impossibly confusing and I can never redo anything and I hate it to death.  Let's try a lib.
Using [[https://gitlab.com/ideasman42/emacs-undo-fu][undo-fu]] because it seems normal.  keybindings down below per usual, but also suggested keybindings [[https://gitlab.com/ideasman42/emacs-undo-fu][in here]] for evil.

(actually I take that back.  I'm going to define them down below in general, but I'm going to use C-u and C-r for it globally, including in insert mode, because fuck that noise.

#+BEGIN_SRC emacs-lisp
(straight-use-package 'undo-fu)
#+END_SRC

Let's see if I can get a restart in

#+BEGIN_SRC emacs-lisp
(straight-use-package 'restart-emacs)

#+END_SRC

Getting sick of having a window with the welcome message show up when I open something from the commandline 

#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC

I don't need these libs until I get to origami in markdown mode in an entire separate config file, but they're generally useful enough that I'd rather load them up right on top.

#+BEGIN_SRC emacs-lisp
  (straight-use-package 'dash)
  (straight-use-package 's)
#+END_SRC

Everything is UTF-8.  EVERYTHING. Borrowed from [[https://www.masteringemacs.org/article/working-coding-systems-unicode-emacs][here.]]  

#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
#+END_SRC



* Frivolity

#+BEGIN_SRC emacs-lisp
(straight-use-package 'zone-nyan)
(require 'zone)
(setq zone-programs [zone-nyan])
(zone-when-idle 1200)
#+END_SRC


* Browsing and Finding Things 

** Files and such  

Spacemacs uses helm, but lots of people who start with helm seem to love Ivy

#+BEGIN_SRC emacs-lisp
(straight-use-package 'counsel)
(ivy-mode 1)
#+END_SRC

I think projectile will be useful for things like project-wide find

#+BEGIN_SRC emacs-lisp
(straight-use-package 'projectile)
(require 'projectile)
(projectile-mode +1)
(setq projectile-completion-system 'ivy)
#+END_SRC


** Commands

Which-key is apparently The Thing 

#+BEGIN_SRC emacs-lisp
(straight-use-package 'which-key)
(require 'which-key)
(which-key-mode)
#+END_SRC


** Characters

#+BEGIN_SRC emacs-lisp
(straight-use-package 'avy)
(require 'avy)
(straight-use-package 'avy-menu)
(require 'avy-menu)

(setq avy-keys (nconc 
                      (number-sequence ?1 ?9)
                      '(?0)
                      (number-sequence ?a ?z)
))
(setq avy-background t)
(setq avy-style 'pre)
#+END_SRC


* Evilify everything because emacs keybindings are horrible

** Base evil 

#+BEGIN_SRC emacs-lisp

(straight-use-package 'evil)
(setq evil-want-keybinding nil)  ;; this is apparently required for evil-collection keybindings.
(require 'evil)
(evil-mode)

#+END_SRC

** Add more evil bindings
Let's get as much evilified as humanly possible just to start, eh?

#+BEGIN_SRC emacs-lisp

(straight-use-package 'evil-commentary)
(require 'evil-commentary)
(evil-commentary-mode)

(straight-use-package 'evil-collection)

(straight-use-package 'evil-org)
(require 'evil-org)
(add-hook 'org-mode-hook 'evil-org-mode)
(evil-org-set-key-theme '(navigation insert textobjects additional calendar))
(require 'evil-org-agenda)
(evil-org-agenda-set-keys)

#+END_SRC

I have keybindings for this down below, but I need a universal bail out of things command.

#+BEGIN_SRC emacs-lisp
(straight-use-package 'evil-escape)
#+END_SRC

I wish I knew how the parsing/evaluation order of these files worked. Can I set a keybinding for something before actually using it? 
I feel like I've seen people actually call functions before defining them in blog posts and such about elisp. 


* Visual 
  
** Theme


Setup

#+BEGIN_SRC emacs-lisp
(straight-use-package 'leuven-theme)

#+END_SRC

Convenience functions

#+BEGIN_SRC emacs-lisp
  (defvar dark-theme 'leuven-dark)
  (defvar light-theme 'leuven)

  (defun disable-all-themes ()
    "disable all active themes."
    (dolist (i custom-enabled-themes)
      (disable-theme i)))

  (defun dark-mode ()
  (interactive)
  (disable-all-themes)
  (load-theme dark-theme t))


  (defun light-mode ()
  (interactive)
  (disable-all-themes)
  (load-theme light-theme t))
#+END_SRC


Dark mode for programming 

I'm not going to use prog-mode-hook on this because it seems to fire it off on org?  but I want org to be light...

#+BEGIN_SRC emacs-lisp
(add-hook 'python-mode-hook 'dark-mode)
#+END_SRC

Light mode for writing

gonna fire this up for markdown mode too.  Maybe it would make sense to define a writing mode hook encompassing org mode and markdown mode?

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'light-mode)
#+END_SRC

This doesn't seem to work perfectly: if I start in an org buffer then open the python buffer, the hook fires and I go dark.  but then if I close the python buffer even though the 
org mode buffer is back on the screen it doesn't go light again.  It does go light if I close the org buffer and reopen it though.  Hmm.  For now I think I'll just toss in a quick keybinding to fix it. 

Start out in light mode

#+BEGIN_SRC emacs-lisp
(light-mode)
#+END_SRC


** Font

#+BEGIN_SRC emacs-lisp

(defvar code-font-string "Inconsolata Light 18")
(defvar prose-font-string "IBM Plex Serif 16")

(defun code-font () 
(interactive)
(set-frame-font code-font-string nil t))

(defun prose-font () 
(interactive)
(set-frame-font prose-font-string nil t))

(code-font)


#+END_SRC

A quick fix for org.

#+BEGIN_SRC emacs-lisp
(setq org-fontify-whole-heading-line t)
#+END_SRC


** GUI tweaks

Get rid of menubar, toolbar, scrollbar


#+BEGIN_SRC emacs-lisp

(menu-bar-mode -1)
(tool-bar-mode -1)
(toggle-scroll-bar -1)
#+END_SRC

Start full-sized

#+BEGIN_SRC emacs-lisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+END_SRC


** Rainbow parens

Can't even begin to edit elisp without this, I want it in this mode noooow.

#+BEGIN_SRC emacs-lisp
(straight-use-package 'rainbow-delimiters)
(add-hook 'org-mode-hook #'rainbow-delimiters-mode)
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+END_SRC


** Modeline


#+BEGIN_SRC emacs-lisp

(straight-use-package 'telephone-line)
(straight-use-package 'nyan-mode)
(require 'nyan-mode)
(nyan-mode)

(setq telephone-line-lhs
      '((evil   . (telephone-line-airline-position-segment
                   telephone-line-evil-tag-segment
                   telephone-line-vc-segment
                   telephone-line-process-segment
                   telephone-line-buffer-segment
                   telephone-line-buffer-modified-segment))
(nil . (telephone-line-nyan-segment))
))
(setq telephone-line-rhs
      '(
;(nil . (telephone-line-nyan-segment))
(evil    . (telephone-line-major-mode-segment)
)))

(telephone-line-mode 1)

#+END_SRC






** Golden ratio

#+BEGIN_SRC emacs-lisp
(straight-use-package 'golden-ratio)
(require 'golden-ratio)
(golden-ratio-mode 1)
#+END_SRC


* Git
#+BEGIN_SRC emacs-lisp

(straight-use-package 'magit)

#+END_SRC

Trying to create the equivalent of ~git add .~ --- the function ~magit-stage-modified~ is close, but appears to require a prefix argument to make it work.

Following the suggestion in [[https://stackoverflow.com/a/6156444/4386239][this SO]] I'm going to just try to force that in. 

Actually, it looks like I don't need to do all that jazz with forced prefix arguments and ~call-interactively~ --- I can just pass it a value.  For now?  Is this
 a bug/undocumented behavior or do I just not understand the function definition?  Is there a way to get emacs to give you the code for a function?

I can probably get rid of that current prefix arg thing.  but this works now, so, why?  


#+BEGIN_SRC emacs-lisp
(defun git-add-all ()
  (interactive)
  (let ((current-prefix-arg '(4)))
  (magit-stage-modified "t")))

#+END_SRC

Ok, now let's see if I can get a straight-up commit going. 

#+BEGIN_SRC emacs-lisp

(defun git-quick-commit ()
(interactive)
(git-add-all)
(magit-commit-create))

#+END_SRC


* Programming 

** Cross- programming language stuff

Completions

#+BEGIN_SRC emacs-lisp
(straight-use-package 'company)
(add-hook 'prog-mode-hook 'company-mode)
(straight-use-package 'company-quickhelp)
(add-hook 'prog-mode-hook 'company-quickhelp-mode)
#+END_SRC

Line numbers

#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook 'linum-mode)
(setq linum-format "%4d \u2502 ")
#+END_SRC

Get rid of visual line mode just in case I switched in from markdown.

#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook (lambda () (visual-line-mode -1)))
#+END_SRC

Make sure code is in a proper code font 

#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook `code-font)
#+END_SRC

Time to take control of my parens. 

evil cleverparens doesn't appear to work though, at least not in this file. It still lets me delete 


#+BEGIN_SRC emacs-lisp

    (straight-use-package 'smartparens)
    (straight-use-package 'evil-cleverparens)
    (add-hook 'smartparens-enabled-hook #'evil-cleverparens-mode)
    (require 'smartparens-config)
    (add-hook 'prog-mode-hook #'smartparens-mode)
    
  ; just to make it easier to work on lisp
    (sp-pair "'" "'" :actions :rem)



#+END_SRC

Syntax checking

#+BEGIN_SRC emacs-lisp
(straight-use-package 'flycheck)
(add-hook 'prog-mode-hook #'global-flycheck-mode)
#+END_SRC

installed on my system: 
pylint (python, via ~pip install pylint~)
eslint (js, via ~npm install -g eslint~)
html-tidy (html, via ~brew install tidy-html5~)
jq (json, via ~brew install jq~)
shellcheck (bash, via ~brew install shellcheck~)
yamllint (yaml, via ~pip install yamllint~)
stylelint (css, via ~npm install -g stylelint stylelint-config-standard~)


** Python  

Currently working: completion, syntax checking via [[https://www.flycheck.org][flycheck]], accessing an interpeter in a window with ~M-x run-python~ 

Not yet tested: sending code out for execution in an interpreter

Not yet implemented: forced code reformatting with [[https://github.com/pythonic-emacs/blacken][blacken]] (do I really want it?); any kind of pipenv/pyenv integration; test runner integration; keybindings 

Globally installed python libraries: jedi, black, autopep8, plyint, yapf.  

Probably needs virtualenv and pipenv integration of some kind to get rid of syntax checking unable to import errors?  
maybe exec-path-from-shell combined with virtualenv will do that though?  (I suspect the interpreter works because of ~exec-path-from-shell~)

- some kind of venv thing like [[https://github.com/marcwebbie/auto-virtualenv][auto-virtualenv]] --- or maybe [[https://github.com/pwalsh/pipenv.el][integrate with pipenv?]] [[https://github.com/pythonic-emacs/pyenv-mode][pyenv mode?]] [[https://github.com/Rokutann/npy.el][npy.el]]? 

#+BEGIN_SRC emacs-lisp
(straight-use-package 'anaconda-mode)
(eval-after-load "company"
 '(add-to-list 'company-backends 'company-anaconda))
(add-hook 'python-mode-hook 'anaconda-mode)
#+END_SRC



* Org

I want to be able to use shift select.

#+BEGIN_SRC emacs-lisp
(setq org-support-shift-select t)
#+END_SRC

I HATE org's link hiding. HATE IT.  It makes it impossible to edit links.  Die die die die.

#+BEGIN_SRC emacs-lisp
(setq org-descriptive-links nil)
#+END_SRC

* Markdown


My markdown config is getting a bit extreme, so I'm going to shove it off entirely into a separate file

#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/markdown/markdown-main.org")
#+END_SRC



* Visual changes between writing and programming

#+BEGIN_SRC emacs-lisp

(defun text-margins ()
  (setq left-margin-width 16)
  (setq right-margin-width 16))
(add-hook 'markdown-mode-hook 'text-margins)

(defun prog-margins ()
  (setq left-margin-width 2)
  (setq right-margin-width 2))
(add-hook 'prog-mode-hook 'prog-margins)

(defun text-linespacing ()
  (setq line-spacing 0.5))
(add-hook 'markdown-mode-hook 'text-linespacing)

(defun prog-linespacing ()
  (setq line-spacing nil))
(add-hook 'prog-mode-hook 'prog-linespacing)

#+END_SRC


* Keybindings

** evil escape

#+BEGIN_SRC emacs-lisp
(evil-escape-mode)
(setq-default evil-escape-delay 0.2)
(global-set-key (kbd "ESC ESC") 'evil-escape)
#+END_SRC

** Bust out General

I think I pretty much just only want these keybindings in normal mode for now.

#+BEGIN_SRC emacs-lisp
(straight-use-package 'general)

(defconst leader "SPC")
(defconst mode-leader ",")
(general-create-definer leader-binding
  :prefix leader
  :states 'normal
  :keymaps 'override) 

(general-create-definer mode-binding
  :prefix mode-leader
  :states 'normal
  :keymaps 'override)

#+END_SRC

** Super global keybindings

Mostly for undo-redo.

#+BEGIN_SRC emacs-lisp

  (general-define-key
  "C-u" 'undo-fu-only-undo
  "C-r" 'undo-fu-only-redo)

#+END_SRC

** Global leader keybindings 

*** Files   :key:


#+BEGIN_SRC emacs-lisp

(leader-binding
"f" '(:ignore t :which-key "Files and Projects")
"ff" 'counsel-find-file
"fs" 'save-buffer
"fn" 'write-file
"fp" '(:ignore t :which-key "Project")
"fpg" 'projectile-grep
"fpf" 'projectile-find-file
"fps" 'projectile-switch-project
 )

#+END_SRC


I think I'd like a special keybinding to get this file open.  spacemacs uses f e d and hence it already in muscle memory I guess
Same with f e r and restart emacs.

#+BEGIN_SRC emacs-lisp

(defun open-config ()
(interactive)
(find-file "~/.emacs.d/readme.org"))

(leader-binding 
"fe" '(:ignore t :which-key "Config/Restart")
"fed" 'open-config
"fer" 'restart-emacs)

#+END_SRC

*** Buffers    :key:

#+BEGIN_SRC emacs-lisp

(leader-binding
"b" '(:ignore t :which-key "Buffers")
"bd" 'kill-this-buffer
"bb" 'ivy-switch-buffer)

#+END_SRC

*** Windows   :key: 

#+BEGIN_SRC emacs-lisp

(leader-binding
"w" '(:ignore t :which-key "Windows")
"w/" 'split-window-right
"w-" 'split-window-below
"wd" 'delete-window
"wx" 'delete-other-windows
"wc" 'other-window
"wf" 'make-frame-command)

#+END_SRC

*** Colors :key:

#+BEGIN_SRC emacs-lisp
  (leader-binding
  "c" '(:ignore t :which-key "Colors")
  "cl" 'light-mode
  "cd" 'dark-mode)
#+END_SRC

*** Elisp/Execute shell commands                                        :key:

#+BEGIN_SRC emacs-lisp
(leader-binding
"e" '(:ignore t :which-key "Elisp")
"ee" 'eval-last-sexp
"eb" 'eval-buffer
"ex" '(:ignore t :which-key "Execute commands and shells")
"exs" 'eshell
"exc" 'shell-command
"exp" '(run-python :which-key "Spawn python interpreter"))
#+END_SRC



*** Help :key: 

#+BEGIN_SRC emacs-lisp

(leader-binding
"h" '(:ignore t :which-key "Help")
"hf" 'describe-function
"hv" 'describe-variable
"ha" 'counsel-apropos)

#+END_SRC

*** Git :key: 

#+BEGIN_SRC emacs-lisp

(leader-binding
"g" '(:ignore t :which-key "Git")
"ga" 'magit-stage-file
"g." 'git-add-all
"gc" 'magit-commit-create
"gp" 'magit-push-current-to-upstream
"gg" 'git-quick-commit
"gu" 'magit-pull-from-upstream
"gi" 'magit-init
"gd" '(:ignore t :which-key "Diffing")
"gdf" '(magit-diff-buffer-file :which-key "Diff current file (use q to exit magit buffer)")
"gda" '(magit-diff-unstaged :which-key "Diff all unstaged files ALREADY TRACKED")
"gr" '(:ignore t :which-key "Remotes")
"gra" 'magit-remote-add)

#+END_SRC


*** Undo-redo :key:

#+BEGIN_SRC emacs-lisp
(leader-binding
"u" '(:ignore t :which-key "Undo/Redo")
"uu" 'undo-fu-only-undo
"ur" 'undo-fu-only-redo)
#+END_SRC

** Modes from comma leader

Markdown keybindings moved to markdown dir because I'm changing it a lot.

#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/markdown/markdown-keybindings.org")
#+END_SRC


*** Org

#+BEGIN_SRC emacs-lisp

(mode-binding 
:keymaps 'org-mode-map
"t" 'org-todo
"f" 'org-cycle 
"l" 'org-insert-link)

#+END_SRC




* Development (of emacs config) conveniences   :dev: 


** Keybinding to make delimiter for elisp blocks with @         

This is slightly black-magic-ey.  add-lisp-delimiters is defined in init.el. 
That function looks for a variable called in-config-file, and, if it's set 
(as it is on the very first line of this file... and apparently it has to be the very 
first line, the second line won't do), then it pastes in the BEGIN_SRC stuff. So I bind it to ampersand, 
because I don't *think* anything else uses @ ...?



#+BEGIN_SRC emacs-lisp

(add-hook 'org-mode-hook 
  (lambda () 
    (evil-global-set-key 'normal (kbd "@") 'add-lisp-delimiters)))

#+END_SRC








* TODO enhancements to make
** Fancier modeline with mode and git enhancements
   - I'm happy with [[https://github.com/dbordak/telephone-line/][telephone-line]] for now, except I'd like to be able to have three color chunks, one reflecting mode, 1 reflecting file save status, and 1 reflecting git status.
** minor keybinding tweaks
     - bind the arrow keys to paging in which-keys (so sue me, I like arrow keys)
** some kind of non-utf-8 utility
   actually, I really want something that will highlight (a) non utf-8 characters, and (b) characters that look like normal ascii characters but aren't.
   - this might be ok just for markdown mode. the point is for copy-paste quotes that introduce shit characters that blow up latex
** swipe-scrolling on the touchpad like with vim
** Language support
*** Javascript
*** HTML
*** Vue.js
*** Clojure
*** shell scripts
*** makefiles
*** JSON
*** YAML
** better undo-redo 
   - maybe try [[https://gitlab.com/ideasman42/emacs-undo-fu][this lib?]]
** window management
      - some way to pin a buffer to a window, so that I can close the window and reopen w/ same buffer there.

** hotkey to reload this config file like spacemacs has
** Markdown enhancements
   - word count in the modeline that just treats markdown punctuation as spaces
   - some way to hide or dimish in-line footnotes.
   - a nice UI to query a CSL json for citations (built on ivy?)
   - highlight and overwrite
** org enhancements
   - fix the weird thing where these internal lists don't tab-indent to same spot
   - MORE KEYBINDINGS for stuff I actually use.


* inspo

[[https://sam217pa.github.io/2016/09/02/how-to-build-your-own-spacemacs/][this person]] [[https://sam217pa.github.io/2016/08/30/how-to-make-your-own-spacemacs/][also]].
[[https://jamiecollinson.com/blog/my-emacs-config/#][this setup]]
[[https://so.nwalsh.com/2020/02/29/dot-emacs%20][this person has a million perf tweaks]]

