# -*- in-config-file: t; lexical-binding: t  -*-

* Python config

Currently working: 

- poetry

- syntax checking via [[https://www.flycheck.org][flycheck]]  

- accessing an interpeter in a window with ~M-x run-python~ 

- sending code out for execution in an interpreter

- linting and such even in a poetry virtualenv

- completion (also including in poetry virtualenv)

- pipenv (and sending code to a shell works, first spawning shell then using run-python to spawn interpreter)

Not yet implemented: 
- forced code reformatting with [[https://github.com/pythonic-emacs/blacken][blacken]] (do I really want it?); 
- test runner integration 

In progress
- keybindings

Not working
- sending code out to a shell in a poetry virtual environment (why the hell not?)



#+BEGIN_SRC emacs-lisp
(straight-use-package 'anaconda-mode)
(straight-use-package 'company-anaconda)
(eval-after-load "company"
 '(add-to-list 'company-backends 'company-anaconda))
(add-hook 'python-mode-hook 'anaconda-mode)
#+END_SRC

Let's try to get poetry integration going.  Apparently that also requires transient and pyvenv packages.

#+BEGIN_SRC emacs-lisp

(straight-use-package 'pyvenv)
(straight-use-package 'transient)
(straight-use-package 'poetry)
(require 'poetry)
(add-hook 'python-mode-hook 'poetry-tracking-mode)

#+END_SRC

I'm kind of hating how poetry behaves re sending projects to shells.  Let's try to get pipenv to do it instead.

#+BEGIN_SRC emacs-lisp
(straight-use-package 'pipenv)
(require 'pipenv)
(add-hook 'python-mode-hook 'pipenv-mode)
#+END_SRC

Convenience function to immediately launch into functionality

(untested)

#+BEGIN_SRC emacs-lisp

(defun pipenv-full-activate ()
  "clean any previous pipenv environment, activate new one, span a shell, then spawn a python"
  (pipenv-deactivate)
  (pipenv-activate)
  (pipenv-shell)
  (run-python))

#+END_SRC



*Notes on virtualenvs* 

following the strategy outlined [[https://stackoverflow.com/a/65740776/4386239][here]] I've created a virtualenv with 

flake8 black autopep8 pylint yapf

and symlinked into PATH to avoid these virtualenv/linting problems.

anaconda-mode seems to automatically install jedi when it's needed.  So that's nice. 

Might want pipenv integration down the line too.  Several possibilities: 

-  [[https://github.com/pwalsh/pipenv.el][integrate with pipenv?]] 

- [[https://github.com/pythonic-emacs/pyenv-mode][pyenv mode?]] 

- [[https://github.com/Rokutann/npy.el][npy.el]]? 
